export function fixture() {
  const now = Date.now(),
    iso = new Date(now).toISOString();
  return {
    fixture: true,
    version: '0.1.0 · fixture',
    observed_at: iso,
    connection: { state: 'online', last_success_at: iso, source: 'local-test-fixture' },
    projects: [
      {
        id: 'control',
        name: 'Aieyra Control',
        root: 'fixture:/projects/control',
        source: 'docs/execution-plan.md',
      },
      { id: 'os', name: 'Aieyra OS', root: 'fixture:/projects/os', source: 'DOCS/current.md' },
      {
        id: 'workspace',
        name: 'Aieyra Workspace',
        root: 'fixture:/projects/workspace',
        source: 'docs/project/EXECUTION_PLAN.md',
      },
      {
        id: 'webside',
        name: 'Aieyra 星空',
        root: 'fixture:/projects/homepage',
        source: 'PROJECT.md',
      },
    ],
    agents: [
      {
        id: 'fixture-os',
        name: 'OS · 副协调',
        project: 'os',
        online: true,
        last_seen: now / 1000 - 25,
        runtime: {
          state: 'running',
          bound: true,
          stale: false,
          observed_at: iso,
          last_activity_at: iso,
          thread_id: 'fixture-thread-os',
        },
      },
      {
        id: 'fixture-home',
        name: '官网 · 体验设计',
        project: 'webside',
        online: true,
        last_seen: now / 1000 - 55,
        runtime: {
          state: 'idle',
          bound: true,
          stale: false,
          observed_at: iso,
          last_activity_at: iso,
          thread_id: 'fixture-thread-home',
        },
      },
      {
        id: 'fixture-workspace',
        name: 'Workspace · 客户端',
        project: 'workspace',
        online: false,
        last_seen: now / 1000 - 480,
        runtime: {
          state: 'idle',
          bound: true,
          observed_at: iso,
          thread_id: 'fixture-thread-workspace',
        },
      },
    ],
    tasks: [
      {
        id: 'fixture-ui',
        project: 'control',
        title: '协作空间 · 桌面与手机界面',
        scope: 'web/ · tests/web/',
        status: 'doing',
        owner: 'fixture-home',
        version: 2,
        evidence: '',
        updated: now / 1000 - 60,
      },
      {
        id: 'fixture-dispatch',
        project: 'os',
        title: '运行时投递与恢复验证',
        scope: 'service/runtime',
        status: 'doing',
        owner: 'fixture-os',
        version: 3,
        evidence: '夹具证据：合成测试用例，不代表生产运行。\n位置 tests/runtime.test.py:42',
        updated: now / 1000 - 120,
      },
      {
        id: 'fixture-mobile',
        project: 'workspace',
        title: '手机端设备配对，等待远端身份接口',
        scope: 'mobile/pairing',
        status: 'blocked',
        owner: 'fixture-workspace',
        version: 1,
        evidence: '',
        updated: now / 1000 - 200,
      },
      {
        id: 'fixture-sky',
        project: 'webside',
        title: '星图阅读路线与天体说明',
        scope: 'components/home-presentation.tsx',
        status: 'delivered',
        owner: 'fixture-home',
        version: 4,
        evidence:
          '这是界面夹具中的示例交付证据。\n源码：components/home-presentation.tsx:120\n检查：合成浏览器检查，不是正式站点验收。',
        updated: now / 1000 - 300,
      },
      {
        id: 'fixture-policy',
        project: 'control',
        title: '共享资源与权限来源核对',
        scope: 'docs/resources.md',
        status: 'planned',
        owner: null,
        version: 1,
        evidence: '',
      },
      {
        id: 'fixture-accepted',
        project: 'control',
        title: '静态资源服务夹具',
        scope: 'tests/web',
        status: 'accepted',
        owner: 'fixture-os',
        version: 3,
        evidence: '夹具验收记录。',
        updated: now / 1000 - 400,
      },
    ],
    messages: [
      {
        seq: 1,
        id: 'fixture-message-1',
        sender: 'fixture-os',
        sender_name: 'OS · 副协调',
        project: 'control',
        kind: 'handoff',
        body: '【合成夹具】这一轮先接通真实状态与消息回执。工位保持各自职责，界面与本地服务按协议对接。',
        created: now / 1000 - 180,
        reply_to: null,
        receipt_count: 2,
      },
      {
        seq: 2,
        id: 'fixture-message-2',
        sender: 'fixture-home',
        sender_name: '官网 · 体验设计',
        project: 'webside',
        kind: 'progress',
        body: '【合成夹具】首版已补齐未知、断线与等待状态。消息进入队列时，仅展示“已排队”，不提前标记收到。',
        created: now / 1000 - 70,
        reply_to: 'fixture-message-1',
        receipt_count: 0,
      },
    ],
    resources: [
      {
        id: 'fixture-projects',
        name: '项目工作目录',
        kind: 'directory',
        project: 'control',
        location: 'fixture:/projects',
        status: 'available',
        observed_at: iso,
        summary: '各项目权威源码与工作文档的共同入口。此处为合成元信息。',
        sensitivity: 'metadata_only',
        size: 4096,
      },
      {
        id: 'fixture-server',
        name: '生产环境 · 服务器清单',
        kind: 'server',
        project: 'os',
        location: 'fixture:/resources/server-inventory.md',
        status: 'registered',
        observed_at: iso,
        summary: '仅登记资料位置，不提供模拟CPU、网络或在线指标。',
        sensitivity: 'metadata_only',
      },
      {
        id: 'fixture-github',
        name: '协作客户端 · GitHub',
        kind: 'github',
        project: 'control',
        location: 'https://github.com/example/control-fixture',
        status: 'registered',
        observed_at: iso,
        summary: '按登记引用查看仓库。未查询远端，不假设仓库已公开或可访问。',
        sensitivity: 'metadata_only',
      },
      {
        id: 'fixture-evidence',
        name: '运行时交付证据',
        kind: 'document',
        project: 'os',
        location: 'fixture:/evidence/runtime-report.md',
        status: 'available',
        observed_at: iso,
        summary: '功能、代码位置和验证结论的来源索引。',
        sensitivity: 'metadata_only',
        size: 8250,
      },
      {
        id: 'fixture-missing',
        name: '尚未接入的远程工作目录',
        kind: 'repository',
        project: 'workspace',
        location: 'fixture:/remote/repository',
        status: 'missing',
        observed_at: iso,
        summary: '保留缺失状态，等待重新登记或连接。',
        sensitivity: 'metadata_only',
      },
    ],
    governance: {
      leader: { name: '协调工位（夹具）', status: 'acting', label: '当前牵头' },
      deputies: [
        {
          id: 'fixture-deputy',
          name: 'OS · 本轮副协调',
          status: 'active',
          scope: 'Control 客户端集成与独立工位分派',
        },
      ],
      assignments: [
        {
          id: 'fixture-assignment',
          owner: 'fixture-home',
          scope: 'web/',
          title: '客户端界面',
          status: 'assigned',
        },
      ],
    },
    deliveries: [
      {
        id: 'fixture-delivery-1',
        target: 'fixture-workspace',
        body: '【合成夹具】请核对手机布局与平台壳的接入方式。',
        state: 'queued',
        message_id: 'fixture-cloud-message',
        queue_id: 'fixture-runtime-queue',
        created_at: new Date(now - 120000).toISOString(),
        updated_at: iso,
        error: null,
      },
    ],
    capabilities: {
      chat: true,
      runtime_dispatch: true,
      resource_refresh: true,
      resource_register: false,
      mobile_pairing: false,
      remote_execution: false,
    },
  };
}
