import {esc, list, text, timestamp, matches, taskRecordLabel, taskRecordState, safeUrl, normalize} from './model.js';
import {updateHTML} from './dom.js';
import {excerpt, messageExcerpt, channelTimeline} from './scene-signals.js';
import {stations, statusLabel, orderedTasks, zoomAt, validCamera, validPosition, readPage} from './observer-model.js';

const $=s=>document.querySelector(s),L=(zh,en)=>language==='en'?en:zh;
const icons={desk:'<path d="M3 11h18M5 11v9m14-9v9M7 4h10v7H7zm3 13h4m-2-5v4"/>',chat:'<path d="M4 4h16v12H9l-5 4zm4 4h8m-8 4h5"/>',tasks:'<path d="M9 6h11M9 12h11M9 18h11M3 5l1 1 2-2m-3 7 1 1 2-2m-3 7 1 1 2-2"/>',shared:'<path d="M3 6h7l2 3h9v11H3zm0 3h9"/>',memory:'<path d="M5 3h13v18H5zm4 5h5m-5 4h5m-5 4h3"/>',refresh:'<path d="M20 8a8 8 0 1 0 0 9M20 3v6h-6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 3h.01"/>',fit:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',home:'<path d="m3 11 9-8 9 8M6 9v12h12V9m-8 12v-7h4v7"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.memory}</svg>`;
const KEY='control-observer-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{}
let language=saved.language==='en'?'en':'zh',project='',query='',camera=validCamera(saved.camera)?saved.camera:null;
let positions=Object.fromEntries(Object.entries(saved.positions||{}).filter(([k,v])=>/^[a-z]+$/.test(k)&&validPosition(v))),pages={},pins=[],selectedSection='stations',rowCache=[],polling=false,lastRefresh=0,disposed=false;
const data={snapshot:{value:null},registry:{value:null},memory:{value:null},attention:{value:null},requirements:{value:null},collaboration:{value:null},cloud:{value:null}};
const paths={snapshot:'/api/snapshot',registry:'/api/registry',memory:'/api/project-memory',attention:'/api/human-requests',requirements:'/api/requirements',collaboration:'/api/collaboration',cloud:'/api/cloud'};
const valid={snapshot:v=>['agents','messages','tasks','resources','projects'].every(k=>Array.isArray(v?.[k])),registry:v=>Array.isArray(v?.seats)&&Array.isArray(v?.governance),memory:v=>Array.isArray(v?.projects),attention:v=>Array.isArray(v?.items),requirements:v=>Array.isArray(v?.items),collaboration:v=>Array.isArray(v?.tasks),cloud:v=>typeof v?.enabled==='boolean'};
const controllers=new Set();
let activeHover=null,hoverSuppressed=null,toastTimer,saveTimer,layoutFrame=0,resizeObserver,space=false,gesture=null,dragged=false;
const pointers=new Map();
function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify({camera,positions,language}));}catch{}},200);}
function notify(message){const node=$('#toast');node.textContent=message;node.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.hidden=true,3200);}
function date(at,long=false){const n=timestamp(at);if(!Number.isFinite(n))return L('尚无记录','No record');return new Intl.DateTimeFormat(language==='en'?'en-GB':'zh-CN',long?{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}:{hour:'2-digit',minute:'2-digit'}).format(new Date(n));}
function projectName(id){return list(data.snapshot.value?.projects).find(p=>p.id===id)?.name||id||L('公共','General');}
function actorName(id){return list(data.snapshot.value?.agents).find(a=>a.id===id)?.name||id||L('未分配','Unassigned');}
function reachable(){return !!data.snapshot.value&&!data.snapshot.error&&Date.now()-data.snapshot.at<180000&&data.snapshot.value.connection?.state==='online';}
const relevant=item=>(!project||item.project===project)&&(!query||matches(item,query));
function filtered(items){return list(items).filter(relevant);}
function empty(title,description=''){return `<p class="empty"><strong>${esc(title)}</strong>${esc(description)}</p>`;}
function statusNote(key){const source=data[key];return source.error?`<p class="section-note warning">${esc(source.value?L('更新暂未成功，保留上次记录。','Update unavailable; showing the last records.'):L('暂时无法读取，请重试。','Unable to read. Please retry.'))} <button class="text-link" data-action="refresh">${L('重试','Retry')}</button></p>`:'';}
function board(id,index,title,count,body,width){return `<section id="board-${id}" data-key="board-${id}" data-board="${id}" class="board" style="width:${width}px" aria-labelledby="title-${id}"><header class="board-head" data-drag="${id}"><span class="board-index">${index}</span><h2 id="title-${id}">${esc(title)}</h2><span class="count">${esc(count)}</span><span class="drag-mark" aria-hidden="true">⠿</span></header><div class="board-body">${body}</div></section>`;}
function paginate(id,items,size,renderItem){const page=readPage(items,pages[id],size);return `${page.items.map(renderItem).join('')}${page.total>size?pager(id,page):''}`;}
function pager(id,p){return `<div class="pager"><button data-page="${id}" data-start="${p.previous}" ${p.start===0?'disabled':''} aria-label="${esc(L('上一页','Previous page'))}">←</button><span>${p.start+1}–${Math.min(p.start+p.items.length,p.total)} / ${p.total}</span><button data-page="${id}" data-start="${p.next}" ${!p.hasNext?'disabled':''} aria-label="${esc(L('下一页','Next page'))}">→</button></div>`;}
const pageSources=new Map();
function pageContent(id,items,size,renderItem,containerClass){pageSources.set(id,{items,size});const p=readPage(items,pages[id],size);return `<div class="${containerClass}">${p.items.map(renderItem).join('')}</div>${p.total>size?pager(id,p):''}`;}

function stationMarkup(s){return `<button class="station" data-key="station-${esc(s.id)}" data-open="station" data-id="${esc(s.id)}" style="--accent:${s.color}" aria-label="${esc(s.name)} · ${esc(statusLabel(s.status.state,language))}"><span class="station-top"><span class="station-emblem">${icon('desk')}</span><span class="station-project">${esc(projectName(s.project))}</span>${s.leader?`<span class="leader">${L('领导','LEAD')}</span>`:''}</span><strong>${esc(s.name||s.id)}</strong><span class="station-status ${s.status.tone}"><i class="dot ${s.status.state==='running'?'active':''}"></i>${esc(statusLabel(s.status.state,language))}</span><span class="station-caption">${esc(s.messages[0]?messageExcerpt(s.messages[0].body,50):L('已入驻 · 等待新的工作记录','Member · awaiting a new work record'))}</span></button>`;}
function feedMarkup(row){const m=row.message,d=row.delivery,body=m?.body||d?.body||'',sender=m?.sender_name||actorName(m?.sender||d?.target),id=m?.id||d?.id,type=m?'message':'delivery';return `<article class="feed-item" data-key="${esc(row.id)}"><div class="feed-meta"><strong>${esc(sender)}</strong><time title="${esc(date(row.at,true))}">${esc(date(row.at))}</time></div><p class="feed-text">${esc(messageExcerpt(body,185))}</p><button class="text-link" data-open="${type}" data-id="${esc(id)}">${esc(L('展开到画布','Open on canvas'))} ↗</button></article>`;}
function taskMarkup(t){const state=taskRecordState(t,reachable());return `<button class="record-button" data-key="task-${esc(t.id)}" data-open="task" data-id="${esc(t.id)}"><span class="record-top"><span class="record-tag ${['blocked','expired','unconfirmed'].includes(state)?'attention':''}">${esc(taskRecordLabel(t,language,reachable()))}</span></span><strong>${esc(t.title||t.id)}</strong><small>${esc(actorName(t.owner))} · ${esc(projectName(t.project))}</small></button>`;}
function resourceMarkup(r){return `<button class="record-button" data-key="resource-${esc(r.id)}" data-open="resource" data-id="${esc(r.id)}"><span class="resource-icon">${icon(r.kind==='directory'?'shared':'memory')}</span><strong>${esc(excerpt(r.name||r.id,45))}</strong><small>${esc(excerpt(r.summary||r.location,68))}</small></button>`;}
function render(){
  const hovering=activeHover;
  const snapshot=data.snapshot.value||{},registry=data.registry.value||{};
  rowCache=stations(registry,snapshot,reachable());
  const allProjects=list(snapshot.projects),active=rowCache.filter(s=>s.status.state==='running').length;
  const rows=rowCache.filter(s=>relevant({...s,summary:s.messages[0]?.body})),tasks=orderedTasks(filtered(snapshot.tasks),reachable());
  const feed=channelTimeline(snapshot).filter(r=>relevant(r.message||r.delivery)).reverse();
  const resources=filtered(snapshot.resources),memories=filtered(data.memory.value?.projects);
  const notes=filtered(snapshot.messages).filter(m=>['handoff','decision','reference','knowledge'].includes(m.kind)).slice().reverse();
  const attention=list(data.attention.value?.items).filter(i=>['waiting_user','decision_recorded'].includes(i.state)&&relevant({...i,project:i.origin?.project,summary:i.question}));
  const requirements=filtered(data.requirements.value?.items);
  const runtimeTasks=filtered(data.collaboration.value?.tasks);
  document.documentElement.lang=language==='en'?'en':'zh-CN';
  updateHTML($('#topbar'),`<div class="brand"><span class="brand-mark" aria-hidden="true">A</span><div><strong>Aieyra Control</strong><small>THE AGENT OFFICE</small></div></div><span class="observe-tag">${L('只读观察','OBSERVATION')}</span><div id="sync-status" class="sync-status ${data.snapshot.error||data.registry.error?'warn':''}" role="status"><i class="dot"></i>${esc(data.snapshot.error?L('连接暂不可用 · 已保留记录','Connection unavailable · records retained'):data.snapshot.value?L('本机同步','Local sync')+' '+date(lastRefresh):L('正在读取','Reading records'))}</div><div class="top-tools"><select id="project-filter" aria-label="${L('筛选项目','Filter by project')}"><option value="">${L('全部项目','All projects')}</option>${allProjects.map(p=>`<option value="${esc(p.id)}" ${project===p.id?'selected':''}>${esc(p.name||p.id)}</option>`).join('')}</select><label class="search-box"><span class="sr-only">${L('搜索画布记录','Search canvas records')}</span><input id="board-search" type="search" placeholder="${L('搜索记录…','Search records…')}" value="${esc(query)}" autocomplete="off"></label><button class="icon-button" data-action="refresh" aria-label="${L('刷新记录','Refresh records')}" ${polling?'disabled':''}>${icon('refresh')}</button><button data-action="language" class="icon-button" aria-label="${L('切换到英文','Switch to Chinese')}">${language==='en'?'中':'EN'}</button><button class="icon-button" data-action="help" aria-label="${L('画布使用说明','Canvas help')}">${icon('help')}</button></div>`);
  const boards=[];
  boards.push(`<div class="masthead" data-key="masthead"><div><span class="eyebrow">${L('工作现场 / 持续更新','WORK IN VIEW / LIVE EDITION')}</span><h1>${L('办公室观察报','The office bulletin')}</h1><p>${L('工作、对话与共享记录，都在这张画布上。','Work, conversations and shared records — together on this canvas.')}</p></div><div class="masthead-stats"><span><strong>${rowCache.length}</strong>${L('常驻工位','Members')}</span><span><strong>${active}</strong>${L('已确认工作中','Confirmed working')}</span><span><strong>${list(snapshot.tasks).length}</strong>${L('任务记录','Task records')}</span></div></div>`);
  boards.push(board('stations','01',L('工位现场','Workstations'),`${rows.length} ${L('席','seats')}`,statusNote('registry')+`<p class="section-note">${L('常驻成员始终在席。执行状态与通信连接分别记录。','Members stay on the board. Execution and communication are recorded separately.')}</p>`+(rows.length?pageContent('stations',rows,8,stationMarkup,'station-grid'):empty(L('等待工位接入','Awaiting workstations'),project||query?L('没有匹配的工位。','No matching stations.'):L('Agent 接入后，工位会出现在这里。','Stations appear when agents join.'))),620));
  boards.push(board('chat','02',L('群聊现场','Conversation'),`${feed.length} ${L('条','records')}`,statusNote('snapshot')+`<p class="section-note">${L('Agent 之间的交流与回执 · 自动更新','Conversations and receipts from agents · updates automatically')}</p>`+(feed.length?pageContent('chat',feed,4,feedMarkup,'feed'):empty(L('还没有对话记录','No conversation yet'),L('消息由 Agent 发送，这里跟随展示。','Agents send messages; this board displays them.'))),430));
  boards.push(board('tasks','03',L('任务进展','Task progress'),`${tasks.length}`,statusNote('snapshot')+(tasks.length?`<div class="task-summary"><span><strong>${tasks.filter(t=>taskRecordState(t,reachable())==='doing').length}</strong>${L('有效接单','Claimed')}</span><span><strong>${tasks.filter(t=>t.status==='blocked').length}</strong>${L('有阻塞','Blocked')}</span><span><strong>${tasks.filter(t=>['delivered','accepted'].includes(t.status)).length}</strong>${L('交付 / 验收','Delivered / accepted')}</span></div>`+pageContent('tasks',tasks,4,taskMarkup,'task-list'):empty(L('暂无登记任务','No registered tasks'),L('工位正在做的事，可以从它的最新动态查看。任务认领由 Agent 登记。','Recent station activity remains visible. Agents register task claims.'))),398));
  boards.push(board('shared','04',L('共享资料','Shared library'),`${resources.length} ${L('份引用','references')}`,statusNote('snapshot')+(resources.length?pageContent('shared',resources,6,resourceMarkup,'resource-list'):empty(L('暂无共享引用','No shared references')))+(notes.length?`<h4 class="section-note" style="margin-top:22px">${L('最近交接与共享信息','Recent handoffs and shared notes')}</h4>`+pageContent('notes',notes,2,m=>`<article class="feed-item" data-key="note-${esc(m.id)}"><div class="feed-meta"><strong>${esc(m.sender_name||actorName(m.sender))}</strong><time>${esc(date(m.created))}</time></div><p class="feed-text">${esc(messageExcerpt(m.body,110))}</p><button class="text-link" data-open="message" data-id="${esc(m.id)}">${L('阅读全文','Read in full')} ↗</button></article>`,'feed'):''),620));
  boards.push(board('memory','05',L('项目档案','Project records'),`${memories.length}`,statusNote('memory')+`<p class="section-note">${L('蓝图、时间线、断点与恢复记录。每一版都属于项目。','Blueprint, timeline, checkpoint and recovery. Every revision belongs to its project.')}</p>`+(memories.length?pageContent('memory',memories,6,m=>`<button class="record-button" data-key="memory-${esc(m.id)}" data-open="memory" data-id="${esc(m.id)}"><span><strong>${esc(m.name||m.id)}</strong><small>${esc(excerpt(m.summary||L('尚未保存记忆','No saved memory'),55))}</small></span><span class="record-tag">v${Number(m.version)||0} ↗</span></button>`,'memory-list'):empty(L('还没有项目档案','No project records'))),430));
  boards.push(board('attention','06',L('关注与需求','Attention & requests'),`${attention.length+requirements.length}`,statusNote('attention')+statusNote('requirements')+(attention.length?pageContent('attention',attention,3,a=>`<button class="record-button" data-key="attention-${esc(a.id)}" data-open="attention" data-id="${esc(a.id)}"><span class="record-tag attention">${L('待沟通','For discussion')}</span><strong>${esc(excerpt(a.question,85))}</strong><small>${esc(projectName(a.origin?.project))}</small></button>`,'task-list'):'')+(requirements.length?pageContent('requirements',requirements,3,r=>`<button class="record-button" data-key="request-${esc(r.id)}" data-open="requirement" data-id="${esc(r.id)}"><span class="record-tag">${L('需求记录','Request')}</span><strong>${esc(excerpt(r.summary||r.title||r.id,85))}</strong><small>${esc(projectName(r.project))}</small></button>`,'task-list'):'')+(!attention.length&&!requirements.length?empty(L('目前没有需要关注的记录','Nothing awaiting attention'),L('需要沟通时，直接在你的 Agent 会话中处理。','Discuss any decisions in your agent session.')):''),398));
  boards.push(board('system','07',L('这张画布','About this canvas'),L('本机','LOCAL'),`<div class="system-row"><span>${L('版本','Version')}</span><strong>${esc(snapshot.version||'—')}</strong></div><div class="system-row"><span>${L('观察范围','Scope')}</span><strong>${L('本机协作记录','Local collaboration')}</strong></div><div class="system-row"><span>${L('云连接','Cloud')}</span><strong>${data.cloud.error?L('状态待同步','Awaiting update'):data.cloud.value?.enabled?esc(data.cloud.value?.user?.name||L('已登录','Signed in')):L('未启用 · 纯本地','Disabled · local only')}</strong></div>${data.cloud.value?.release?.manifest?`<div class="system-row"><span>${L('发行通知','Release')}</span><strong>${esc(data.cloud.value.release.manifest.version)}</strong></div>`:''}<div class="system-row"><span>${L('上次读取','Last read')}</span><strong>${esc(lastRefresh?date(lastRefresh,true):'—')}</strong></div><p class="section-note" style="margin:16px 0 0">${L('此处只读。让 Agent 发送消息、管理工位和维护档案。','Read only. Ask your agent to send messages, manage stations and maintain records.')}</p><button class="text-link" data-action="help">${L('平移、缩放与键盘操作','Pan, zoom and keyboard controls')} ↗</button>`,398));
  if(runtimeTasks.length)boards.push(board('runtime','08',L('原生执行记录','Native execution'),`${runtimeTasks.length}`,statusNote('collaboration')+pageContent('runtime',runtimeTasks,4,t=>`<button class="record-button" data-key="runtime-${esc(t.id)}" data-open="runtime" data-id="${esc(t.id)}"><span class="record-tag">${esc(runtimeLabel(t))}</span><strong>${esc(t.title||t.id)}</strong><small>${esc(excerpt(list(t.activity?.items).at(-1)?.command||list(t.activity?.items).at(-1)?.title||t.error||'',90))}</small></button>`,'task-list'),430));
  boards.push(...pins.map(pinMarkup));
  updateHTML($('#world'),boards.join(''));
  updateHTML($('#dock'),[['stations','desk',L('工位','Seats')],['chat','chat',L('群聊','Chat')],['tasks','tasks',L('任务','Tasks')],['shared','shared',L('共享','Shared')],['memory','memory',L('档案','Records')]].map(([id,glyph,label])=>`<button data-jump="${id}" aria-current="${selectedSection===id}">${icon(glyph)}<span>${label}</span></button>`).join('')+`<span class="dock-divider"></span><button data-action="home" aria-label="${L('回到首页视角','Home view')}">${icon('home')}<span>${L('首页','Home')}</span></button><button data-action="fit" aria-label="${L('总览整个画布','Fit the canvas')}">${icon('fit')}<span>${L('总览','Fit')}</span></button><div class="zoom-control"><button data-action="zoom-out" aria-label="${L('缩小','Zoom out')}">−</button><output id="zoom-level">${Math.round((camera?.z||1)*100)}%</output><button data-action="zoom-in" aria-label="${L('放大','Zoom in')}">+</button></div><button class="arrange-button" data-action="arrange">${L('归整','Arrange')}</button>`);
  $('#canvas-hint').textContent=L('拖动空白处平移 · Ctrl + 滚轮缩放\n点击工位或记录，展开全文','Drag background to pan · Ctrl + wheel to zoom\nClick a station or record to read');
  $('#board-search').value=query;
  resizeObserver?.disconnect();document.querySelectorAll('.board').forEach(el=>resizeObserver?.observe(el));
  layout();if(!camera)home(false);else applyCamera();
  if(hovering?.isConnected)showHover(hovering);
}

function runtimeLabel(t){const at=timestamp(t.observed_at),confirmed=!data.collaboration.error&&data.collaboration.value?.available===true&&data.collaboration.value?.stale!==true&&t.stale===false&&Number.isFinite(at)&&Date.now()-at<=30000&&at-Date.now()<60000;const labels={running:L('执行中','Running'),completed:L('已完成','Completed'),failed:L('失败','Failed'),cancelled:L('已取消','Cancelled'),idle:L('待命','Ready'),waiting_user:L('等待沟通','Awaiting input')};return confirmed?(labels[t.state]||L('状态待同步','Awaiting update')):L('历史执行记录','Recorded execution');}

function pair(label,value){return `<div class="detail-pair"><dt>${esc(label)}</dt><dd>${esc(text(value)||'—')}</dd></div>`;}
function full(value){return `<p class="full-text">${esc(text(value)||L('暂无记录','No record'))}</p>`;}
function pinMarkup(pin){
  let body='',title='';const snap=data.snapshot.value||{};
  const record=pin.record;
  if(pin.type==='station'){
    const s=rowCache.find(s=>s.id===pin.id)||record;title=s.name||s.id;
    const status=rowCache.some(r=>r.id===pin.id)?s.status:{state:'sync',tone:'quiet'};
    body=`<h3>${esc(title)}</h3><span class="station-status ${status.tone}"><i class="dot"></i>${esc(statusLabel(status.state,language))}</span><p class="detail-notice">${L('通信连接没有续期，不能据此认定 Agent 停工。执行状态只根据当前可确认的记录显示。','A communication lease does not determine whether an agent is working. Execution status uses only verifiable observations.')}</p><dl>${pair(L('所属项目','Project'),projectName(s.project))}${pair(L('最新活动','Last activity'),date(s.status?.at,true))}${pair(L('通信状态','Communication'),s.agent?.runtime?.session_state==='connected'&&s.agent?.runtime?.stale===false?L('已连接','Connected'):L('待重新同步','Awaiting reconnection'))}</dl><h4>${L('最近动态','Recent activity')}</h4>`+(s.messages?.length?s.messages.slice(0,6).map(m=>`<article class="feed-item"><div class="feed-meta"><time>${esc(date(m.created,true))}</time></div>${full(m.body)}</article>`).join(''):full(L('暂无已记录动态。','No recorded activity.')))+`<h4>${L('登记任务','Registered tasks')}</h4>`+(s.tasks?.length?s.tasks.map(taskMarkup).join(''):full(L('暂无登记任务。','No registered tasks.')))+`<details data-preserve-open><summary>${L('工位与会话标识','Station and session identifiers')}</summary><dl>${pair('Station',s.id)}${pair('Agent',s.actor_id)}${pair('Native session',s.station_binding?.native_session_id)}${pair('Transport',s.agent?.runtime?.thread_id)}</dl></details>`;
  }else if(pin.type==='message'||pin.type==='delivery'){
    const r=list(snap[pin.type==='message'?'messages':'deliveries']).find(r=>r.id===pin.id)||record;title=pin.type==='message'?L('群聊记录','Conversation record'):L('消息与回执','Message & receipt');body=`<h3>${esc(r.sender_name||actorName(r.sender||r.target))}</h3><p class="detail-meta">${esc(date(r.created||r.created_at,true))} · ${esc(projectName(r.project))}</p>`+full(r.body)+(r.reply?`<h4>${L('Agent 答复','Agent reply')}</h4>`+full(r.reply):'');
  }else if(pin.type==='task'){
    const t=list(snap.tasks).find(r=>r.id===pin.id)||record;title=L('任务记录','Task record');body=`<h3>${esc(t.title||t.id)}</h3><p class="detail-meta">${esc(taskRecordLabel(t,language,reachable()))}</p><dl>${pair(L('项目','Project'),projectName(t.project))}${pair(L('负责人','Owner'),actorName(t.owner))}${pair(L('更新时间','Updated'),date(t.updated||t.updated_at,true))}</dl><h4>${L('说明','Description')}</h4>`+full(t.description||t.summary||t.body||t.title)+`<h4>${L('证据','Evidence')}</h4>`+full(t.evidence)+`<p class="detail-notice">${L('认领、交付和验收是不同记录；认领不代表已经执行。','Claim, delivery and acceptance are separate records. A claim does not prove execution.')}</p>`;
  }else if(pin.type==='resource'){
    const r=list(snap.resources).find(r=>r.id===pin.id)||record;title=L('共享资料','Shared reference');const url=safeUrl(r.location);body=`<h3>${esc(r.name||r.id)}</h3><p class="detail-meta">${esc(projectName(r.project))} · ${esc(r.kind)}</p>`+full(r.summary)+`<h4>${L('资料位置','Location')}</h4>`+full(r.location)+(url?`<p><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${L('打开来源','Open source')} ↗</a></p>`:'')+`<dl>${pair(L('状态','Status'),({available:L('可读取','Available'),registered:L('已登记','Registered'),missing:L('路径不存在','Missing'),unreachable:L('暂不可达','Unavailable')})[r.status]||L('待核对','Unconfirmed'))}${pair(L('元信息更新','Metadata updated'),date(r.observed_at,true))}</dl><p class="detail-notice">${L('这里只展示已登记引用与说明，资料仍保留在原位置。','References and descriptions only. Content stays at its source.')}</p>`;
  }else if(pin.type==='memory'){
    title=L('项目档案','Project records');const v=pin.value,m=v?.memory;body=`<h3>${esc(projectName(pin.id))}</h3>${pin.loading?`<p role="status">${L('正在读取档案…','Reading records…')}</p>`:''}${pin.error?`<p class="warning" role="alert">${L('档案读取失败。','Unable to read records.')} <button class="text-link" data-memory-read="${esc(pin.key)}">${L('重试','Retry')}</button></p>`:''}${m?`<p class="detail-meta">v${Number(m.version)||0} · ${esc(date(m.created_at,true))}${pin.version?` · ${L('历史版本','Historical revision')}`:''}</p>${full(m.summary)}<div class="memory-controls"><button class="text-link" data-memory-read="${esc(pin.key)}">${L('读取当前版本','Read current revision')}</button></div>${[['checkpoint','当前断点与下一步','Checkpoint & next steps'],['blueprint','项目蓝图','Blueprint'],['timeline','历史时间线','Timeline'],['recovery','备份与恢复','Backup & recovery'],['index','工程索引','Project index']].map(([k,zh,en])=>`<h4>${L(zh,en)}</h4>${full(m.sections[k])}`).join('')}<h4>${L('历史版本','Revision history')}</h4>${list(pin.history).map(h=>`<button class="record-button" data-memory-read="${esc(pin.key)}" data-version="${Number(h.version)}">v${Number(h.version)} · ${esc(excerpt(h.summary,90))}<small>${esc(date(h.created_at,true))}</small></button>`).join('')}`:''}`;
  }else if(pin.type==='runtime'){
    const t=list(data.collaboration.value?.tasks).find(r=>r.id===pin.id)||record;title=L('原生执行记录','Native execution');body=`<h3>${esc(t.title||t.id)}</h3><p class="detail-meta">${esc(runtimeLabel(t))} · ${esc(date(t.observed_at,true))}</p>`+(t.error?`<h4>${L('问题记录','Issue')}</h4>`+full(t.error):'')+`<h4>${L('已记录步骤','Recorded steps')}</h4>`+list(t.activity?.items).filter(a=>a.hidden!==true).map(a=>`<article class="feed-item"><div class="feed-meta"><strong>${esc(a.tool||a.title||a.id)}</strong><span>${esc(a.state)}</span></div>${full(a.command||a.title||a.action)}${a.detail?full(a.detail):''}</article>`).join('')+`<h4>${L('产物引用','Artifact references')}</h4>`+list(t.artifacts).map(a=>full(a.path||a.name)).join('');
  }else if(pin.type==='attention'){
    const r=list(data.attention.value?.items).find(r=>r.id===pin.id)||record;title=L('需要沟通','For discussion');body=`<h3>${esc(r.question)}</h3><p class="detail-notice">${L('请在你的 Agent 会话中沟通，由 Agent 记录决定。','Discuss this in your agent session. Your agent records the decision.')}</p><h4>${L('已知事实','Known facts')}</h4>`+full(r.facts)+`<h4>${L('建议','Recommendation')}</h4>`+full(r.recommendation)+list(r.options).map(o=>`<h4>${esc(o.label)}</h4>${full(o.description)}`).join('');
  }else if(pin.type==='requirement'){
    const r=pin.value||record;title=L('需求记录','Request record');body=`<h3>${esc(r.summary||r.title||r.id)}</h3><p class="detail-meta">${esc(projectName(r.project))} · v${Number(r.version)||0}</p>${pin.loading?`<p role="status">${L('正在读取…','Reading…')}</p>`:''}${pin.error?`<p class="warning">${L('详情暂不可用，保留列表摘要。','Detail unavailable; showing the list summary.')} <button class="text-link" data-requirement-read="${esc(pin.key)}">${L('重试','Retry')}</button></p>`:''}`+full(r.description||r.body||r.summary)+`<h4>${L('关联任务','Linked tasks')}</h4>`+list(r.tasks).map(t=>`<p class="full-text">${esc(t.title||t.id)} · ${esc(taskRecordLabel(t,language,reachable()))}</p>`).join('');
  }else{
    title=L('画布使用说明','Canvas guide');body=`<h3>${L('让工作自己展开','Let the work unfold')}</h3><p class="help-lines">${L('拖动空白处平移画布；滚轮上下移动，Shift + 滚轮左右移动。Ctrl / ⌘ + 滚轮缩放，触摸屏可双指缩放。','Drag empty space to pan. Wheel moves vertically; Shift + wheel moves horizontally. Ctrl / ⌘ + wheel zooms. Pinch on touch screens.')}<br><br>${L('拖动卡片标题可摆放位置。底部导航直接定位到对应区块；“归整”恢复报板排列。视角和布局会保留。','Drag a card header to reposition it. The navigation jumps to a section. Arrange restores the bulletin layout. View and layout are remembered.')}<br><br>${L('鼠标停留只显示简短预览。点击工位、对话或资料，在画布中展开完整记录；可同时保留多张详情卡片。','Hover previews are brief. Click a station, conversation or reference to open a full card on the canvas. Several detail cards can stay open.')}<br><br><kbd>Tab</kbd> ${L('选择条目','select an item')} · <kbd>Enter</kbd> ${L('展开','open')} · <kbd>Esc</kbd> ${L('收起预览 / 详情','dismiss preview / detail')}<br><kbd>↑ ↓ ← →</kbd> ${L('平移','pan')} · <kbd>+ −</kbd> ${L('缩放','zoom')} · <kbd>Home</kbd> ${L('首页视角','home view')}<br><br>${L('这里是观察窗口。发送消息、变更任务与维护项目，交给你的 Agent。','This is an observation window. Ask your agent to send messages, change tasks and maintain projects.')}</p>`;
  }
  return `<section class="board detail-board" data-key="pin-${esc(pin.key)}" data-pin="${esc(pin.key)}" style="width:570px" aria-label="${esc(title)}"><header class="board-head" data-drag="pin:${esc(pin.key)}"><span class="board-index">↗</span><h2>${esc(title)}</h2><span class="count">${L('已展开','PINNED')}</span><button data-close-pin="${esc(pin.key)}" aria-label="${L('关闭此详情','Close this detail')}">×</button></header><div class="board-body">${body}</div></section>`;
}

function layout(){
  const columns=innerWidth<700?[{x:0,ids:['stations','chat','tasks','shared','memory','attention','system','runtime']}]:[{x:0,ids:['stations','shared']},{x:644,ids:['chat','memory','runtime']},{x:1098,ids:['tasks','attention','system']}];
  for(const col of columns){let y=140;for(const id of col.ids){const el=$('#board-'+id);if(!el)continue;const pos=positions[id]||{x:col.x,y};el.style.left=pos.x+'px';el.style.top=pos.y+'px';y+=el.offsetHeight+24;}}
  let y=140;for(const p of pins){const el=[...document.querySelectorAll('[data-pin]')].find(e=>e.dataset.pin===p.key);if(!el)continue;const pos=p.pos||{x:innerWidth<700?innerWidth:1530,y};el.style.left=pos.x+'px';el.style.top=pos.y+'px';y+=el.offsetHeight+24;}
}
function scheduleLayout(){if(layoutFrame)return;layoutFrame=requestAnimationFrame(()=>{layoutFrame=0;layout();});}
function viewport(){return $('#main');}
function applyCamera(){if(!camera)return;$('#world').style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.z})`;const out=$('#zoom-level');if(out)out.textContent=Math.round(camera.z*100)+'%';hideHover();persist();}
function home(announce=true){const v=viewport(),z=innerWidth<700?1:Math.max(.35,Math.min(1,(v.clientWidth-72)/1496));camera={x:innerWidth<700?14:(v.clientWidth-1496*z)/2,y:28,z};selectedSection='stations';applyCamera();updateCurrent();if(announce)notify(L('已回到办公室首页','Returned to the office view'));}
function focusBoard(id,focus=false){const el=$('#board-'+id);if(!el)return;selectedSection=id;focusElement(el,focus);updateCurrent();}
function updateCurrent(){document.querySelectorAll('[data-jump]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.jump===selectedSection)));}
function focusElement(el,focus=false){const v=viewport(),z=Math.max(.35,Math.min(1,(v.clientWidth-32)/el.offsetWidth));camera={x:(v.clientWidth-el.offsetWidth*z)/2-el.offsetLeft*z,y:24-el.offsetTop*z,z};applyCamera();if(focus)el.querySelector('button')?.focus({preventScroll:true});}
function fit(){const elements=[...document.querySelectorAll('.board,.masthead')];const left=Math.min(...elements.map(e=>e.offsetLeft)),top=Math.min(...elements.map(e=>e.offsetTop)),right=Math.max(...elements.map(e=>e.offsetLeft+e.offsetWidth)),bottom=Math.max(...elements.map(e=>e.offsetTop+e.offsetHeight));const v=viewport(),z=Math.max(.2,Math.min(1,(v.clientWidth-50)/(right-left),(v.clientHeight-120)/(bottom-top)));camera={z,x:(v.clientWidth-(right-left)*z)/2-left*z,y:25-top*z};applyCamera();}
function hideHover(){activeHover=null;$('#hover-preview').hidden=true;document.querySelectorAll('[aria-describedby="hover-preview"]').forEach(el=>el.removeAttribute('aria-describedby'));}
function showHover(button){
  if(!button?.isConnected||hoverSuppressed===button)return;
  const s=rowCache.find(s=>s.id===button.dataset.id);if(!s)return;const el=$('#hover-preview');activeHover=button;el.innerHTML=`<strong>${esc(s.name)}</strong><small>${esc(statusLabel(s.status.state,language))} · ${esc(date(s.status.at))}</small><p>${esc(messageExcerpt(s.messages[0]?.body||L('暂无新动态。工位保留，等待下一次状态同步。','No new activity. Station retained, awaiting the next update.'),112))}</p><small>${L('点击展开完整记录 ↗','Click to open the full record ↗')}</small>`;el.hidden=false;
  const box=button.getBoundingClientRect(),w=el.offsetWidth,h=el.offsetHeight;const left=box.right+w+14<innerWidth?box.right+12:Math.max(12,box.left-w-12);el.style.left=Math.min(innerWidth-w-12,left)+'px';el.style.top=Math.max(12,Math.min(innerHeight-h-12,box.top))+'px';button.setAttribute('aria-describedby','hover-preview');
}
function lookup(type,id){const s=data.snapshot.value||{};return type==='station'?rowCache.find(r=>r.id===id):type==='memory'?list(data.memory.value?.projects).find(r=>r.id===id):type==='attention'?list(data.attention.value?.items).find(r=>r.id===id):type==='requirement'?list(data.requirements.value?.items).find(r=>r.id===id):type==='runtime'?list(data.collaboration.value?.tasks).find(r=>r.id===id):list(s[{message:'messages',delivery:'deliveries',task:'tasks',resource:'resources'}[type]]).find(r=>r.id===id);}
function openPin(type,id,origin){
  hideHover();let pin=pins.find(p=>p.type===type&&p.id===id);if(!pin){const record=lookup(type,id);if(!record&&type!=='help')return;pin={key:'p'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),type,id,record,origin};pins.push(pin);}
  render();const node=[...document.querySelectorAll('[data-pin]')].find(e=>e.dataset.pin===pin.key);focusElement(node);node.querySelector('button')?.focus({preventScroll:true});
  if(type==='memory'&&!pin.value&&!pin.loading)void readMemory(pin);if(type==='requirement'&&!pin.value&&!pin.loading)void readRequirement(pin);
}
function closePin(key){const pin=pins.find(p=>p.key===key);if(!pin)return;pin.token=Symbol();pins=pins.filter(p=>p!==pin);render();if(pin.origin?.isConnected){const el=pin.origin.closest('.board');if(el)focusElement(el);pin.origin.focus({preventScroll:true});}else home(false);}
async function get(path){const c=new AbortController();controllers.add(c);const timer=setTimeout(()=>c.abort(),8000);try{const r=await fetch(path,{method:'GET',credentials:'same-origin',cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error('read_failed');return await r.json();}finally{clearTimeout(timer);controllers.delete(c);}}
async function readMemory(pin,version){const token=Symbol();pin.token=token;pin.loading=true;pin.error=false;pin.version=version||null;pin.value=null;render();try{const [v,h]=await Promise.all([get('/api/project-memory?project='+encodeURIComponent(pin.id)+(version?'&version='+version:'')),get('/api/project-memory?project='+encodeURIComponent(pin.id)+'&history=1')]);if(pin.token!==token||!pins.includes(pin))return;if(v?.memory?.project!==pin.id||!v.memory.sections||!Array.isArray(h?.revisions))throw Error('invalid_memory');pin.value=v;pin.history=h.revisions;}catch{if(pin.token===token)pin.error=true;}finally{if(pin.token===token&&pins.includes(pin)){pin.loading=false;render();}}}
async function readRequirement(pin){const token=Symbol();pin.token=token;pin.loading=true;pin.error=false;render();try{const r=await get('/api/requirement?id='+encodeURIComponent(pin.id));if(pin.token!==token||!pins.includes(pin))return;if(r?.id!==pin.id)throw Error('invalid_requirement');pin.value=r;}catch{if(pin.token===token)pin.error=true;}finally{if(pin.token===token&&pins.includes(pin)){pin.loading=false;render();}}}
async function refresh(){if(polling||disposed)return;polling=true;render();await Promise.all(Object.entries(paths).map(async([key,path])=>{try{const v=await get(path);if(!valid[key](v))throw Error('invalid_response');data[key]={value:key==='snapshot'?normalize(v):v,at:Date.now(),error:false};if(key==='snapshot')lastRefresh=Date.now();}catch{data[key].error=true;}}));polling=false;if(!disposed)render();}

$('#app').innerHTML=`<div class="shell"><header class="topbar" id="topbar"></header><main id="main" class="viewport" tabindex="0" aria-label="${L('无限观察画布','Infinite observation canvas')}"><div id="world" class="world"></div><p id="canvas-hint" class="canvas-hint"></p><nav id="dock" class="dock" aria-label="${L('画布导航','Canvas navigation')}"></nav></main></div><aside id="hover-preview" class="hover-preview" role="tooltip" hidden></aside>`;
resizeObserver=new ResizeObserver(scheduleLayout);
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||b.disabled)return;if(dragged){e.preventDefault();return;}
  if(b.dataset.open){openPin(b.dataset.open,b.dataset.id,b);return;}
  if(b.dataset.closePin){closePin(b.dataset.closePin);return;}
  if(b.dataset.jump){focusBoard(b.dataset.jump);return;}
  if(b.dataset.page){const source=pageSources.get(b.dataset.page),start=Number(b.dataset.start);pages[b.dataset.page]={start,anchor:start?source?.items[start]?.id:null};render();return;}
  if(b.dataset.memoryRead){const p=pins.find(p=>p.key===b.dataset.memoryRead);if(p)void readMemory(p,Number(b.dataset.version)||undefined);return;}
  if(b.dataset.requirementRead){const p=pins.find(p=>p.key===b.dataset.requirementRead);if(p)void readRequirement(p);return;}
  const action=b.dataset.action;
  if(action==='refresh')void refresh();if(action==='home')home();if(action==='fit')fit();
  if(action==='language'){language=language==='en'?'zh':'en';render();persist();}
  if(action==='help')openPin('help','guide',b);
  if(action==='arrange'){positions={};pins.forEach(p=>delete p.pos);layout();home();persist();notify(L('已恢复报板排列','Bulletin layout restored'));}
  if(action==='zoom-in'||action==='zoom-out'){const v=viewport();camera=zoomAt(camera,action==='zoom-in'?1.18:1/1.18,{x:v.clientWidth/2,y:v.clientHeight/2});applyCamera();}
});
document.addEventListener('input',e=>{if(e.target.id==='board-search'){query=e.target.value;pages={};render();}});
document.addEventListener('change',e=>{if(e.target.id==='project-filter'){project=e.target.value;pages={};render();home(false);}});
document.addEventListener('pointerover',e=>{const button=e.target.closest('.station');if(button&&e.pointerType!=='touch'&&!gesture)showHover(button);});
document.addEventListener('pointerout',e=>{const button=e.target.closest('.station');if(button&&!button.contains(e.relatedTarget)){if(activeHover===button)hideHover();if(hoverSuppressed===button)hoverSuppressed=null;}});
document.addEventListener('focusin',e=>{
  const el=e.target;if(!el.closest('#world'))return;
  requestAnimationFrame(()=>{if(document.activeElement!==el)return;const r=el.getBoundingClientRect(),v=viewport().getBoundingClientRect();if(r.top<v.top+8||r.bottom>v.bottom-105||r.left<8||r.right>innerWidth-8){camera.x+=Math.max(8-r.left,Math.min(0,innerWidth-8-r.right));camera.y+=Math.max(v.top+20-r.top,Math.min(0,v.bottom-115-r.bottom));applyCamera();}if(el.matches('.station'))showHover(el);});
});
document.addEventListener('focusout',e=>{if(e.target===activeHover)hideHover();});
const canvas=viewport();
canvas.addEventListener('wheel',e=>{if(e.target.closest('#dock'))return;e.preventDefault();const factor=e.deltaMode===1?16:e.deltaMode===2?canvas.clientHeight:1,dx=e.deltaX*factor,dy=e.deltaY*factor;if(e.ctrlKey||e.metaKey){const r=canvas.getBoundingClientRect();camera=zoomAt(camera,Math.exp(-Math.max(-200,Math.min(200,dy))*.004),{x:e.clientX-r.left,y:e.clientY-r.top});}else{camera.x-=e.shiftKey?dy:dx;camera.y-=e.shiftKey?dx:dy;}applyCamera();},{passive:false});
canvas.addEventListener('pointerdown',e=>{
  if(e.target.closest('#dock')||e.button!==0&&e.button!==1)return;
  const point={x:e.clientX,y:e.clientY};pointers.set(e.pointerId,point);
  if(pointers.size===2){const [a,b]=[...pointers.values()];gesture={type:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),mid:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},camera:{...camera}};dragged=true;hideHover();e.preventDefault();canvas.setPointerCapture(e.pointerId);return;}
  const handle=e.target.closest('[data-drag]'),interactive=e.target.closest('button,a,input,select,summary');
  if(e.pointerType==='touch'&&interactive){gesture={type:'touchpending',start:point,camera:{...camera}};dragged=false;return;}
  const background=(!e.target.closest('.board')||e.pointerType==='touch')&&!interactive;
  if(!space&&e.button!==1&&(!background&&(!handle||interactive)))return;
  const id=handle&&!space&&e.button!==1?handle.dataset.drag:null,el=handle?.closest('.board');
  gesture={type:id?'card':'pan',id,start:point,camera:{...camera},pos:el?{x:el.offsetLeft,y:el.offsetTop}:null};dragged=false;hideHover();canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging');e.preventDefault();
});
canvas.addEventListener('pointermove',e=>{
  if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!gesture)return;
  if(gesture.type==='pinch'&&pointers.size>=2){const [a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},r=canvas.getBoundingClientRect();camera=zoomAt(gesture.camera,Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,gesture.distance),{x:gesture.mid.x-r.left,y:gesture.mid.y-r.top});camera.x+=mid.x-gesture.mid.x;camera.y+=mid.y-gesture.mid.y;applyCamera();return;}
  if(gesture.type==='pinch')return;const dx=e.clientX-gesture.start.x,dy=e.clientY-gesture.start.y;if(Math.abs(dx)+Math.abs(dy)>5)dragged=true;
  if(gesture.type==='touchpending'){if(!dragged)return;gesture.type='pan';canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging');hideHover();}
  if(gesture.type==='pan'){camera={...gesture.camera,x:gesture.camera.x+dx,y:gesture.camera.y+dy};applyCamera();}
  else{const pos={x:gesture.pos.x+dx/camera.z,y:gesture.pos.y+dy/camera.z};if(gesture.id.startsWith('pin:')){const p=pins.find(p=>p.key===gesture.id.slice(4));if(p)p.pos=pos;}else positions[gesture.id]=pos;layout();persist();}
});
function endGesture(e){pointers.delete(e.pointerId);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(pointers.size===0||gesture?.type!=='pinch'){gesture=null;canvas.classList.remove('dragging');setTimeout(()=>dragged=false,0);}}
canvas.addEventListener('pointerup',endGesture);canvas.addEventListener('pointercancel',endGesture);
window.addEventListener('blur',()=>{space=false;pointers.clear();gesture=null;dragged=false;canvas.classList.remove('dragging');hideHover();});
document.addEventListener('keydown',e=>{
  if(e.isComposing)return;
  if(e.key==='Escape'){if(activeHover){hoverSuppressed=activeHover;hideHover();}else if(pins.length)closePin(pins.at(-1).key);e.preventDefault();return;}
  if(e.target.matches('input,select,textarea')||e.target.isContentEditable)return;
  if(e.code==='Space'&&!e.target.closest('button,summary')){space=true;e.preventDefault();}
  if(e.target!==canvas)return;
  const movement={ArrowLeft:[90,0],ArrowRight:[-90,0],ArrowUp:[0,90],ArrowDown:[0,-90]};
  if(movement[e.key]){e.preventDefault();camera.x+=movement[e.key][0];camera.y+=movement[e.key][1];applyCamera();}
  if(e.key==='Home'){e.preventDefault();home(false);}if(['+','=','-'].includes(e.key)){e.preventDefault();camera=zoomAt(camera,e.key==='-'?1/1.18:1.18,{x:canvas.clientWidth/2,y:canvas.clientHeight/2});applyCamera();}
});
document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});
window.addEventListener('resize',()=>{hideHover();scheduleLayout();});
window.addEventListener('pagehide',()=>{disposed=true;controllers.forEach(c=>c.abort());});
window.addEventListener('pageshow',e=>{if(e.persisted){disposed=false;void refresh();}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh();});
window.controlPlatform?.onHumanRequestOpen?.(()=>{focusBoard('attention',true);});
render();void refresh();setInterval(()=>{if(!document.hidden&&!disposed)void refresh();},8000);
