import {esc,list,text,matches,timestamp} from './model.js';
import {excerpt,messageExcerpt} from './scene-signals.js';
import {focusVisible} from './focus.js';

export function createSharedSpace({api,getSnapshot,getLanguage,writeReady,onChange}){
  let category='all',query='',formOpen=false,draft={name:'',location:'',summary:'',kind:'document',project:''},pending=null,busy=false,error='',notice='',completionFocus=false;
  const key='control-shared-reference-v1',L=(zh,en)=>getLanguage()==='en'?en:zh;
  try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved?.id&&saved?.payload){pending=saved;draft={...draft,...saved.payload};formOpen=true;}}catch{}
  const persist=()=>{try{if(pending)sessionStorage.setItem(key,JSON.stringify(pending));else sessionStorage.removeItem(key);}catch{}};
  const kindLabel=kind=>({document:L('文件','File'),directory:L('目录','Folder'),repository:L('代码','Code'),github:'GitHub',server:L('服务器','Server')})[kind]||L('资料','Resource');
  function saved(){
    const restore=completionFocus&&(document.activeElement===document.body||document.activeElement?.closest('#shared-form'));
    pending=null;persist();formOpen=false;draft={name:'',location:'',summary:'',kind:'document',project:''};
    notice=L('引用已登记，文件仍保留在原位置。','Reference saved. The file stays at its source.');onChange(true);
    if(restore)focusVisible('[data-shared="add"]');completionFocus=false;
  }
  async function lookup(){if(!pending||busy)return;completionFocus=Boolean(document.activeElement?.closest('#shared-form'));busy=true;error='';onChange();try{const value=await api('/api/snapshot');const found=list(value.resources).find(r=>r.id===pending.id&&r.location===pending.payload.location&&r.name===pending.payload.name);if(found){saved();}else error=L('尚未查到，保留原引用继续核对','Not found yet; keep this reference and check again');}catch{error=L('暂时无法核对','Could not check the reference');}finally{busy=false;onChange();}}
  async function submit(){
    if(busy||pending||!writeReady()||getSnapshot().capabilities?.resource_register!==true||!draft.name.trim()||!draft.location.trim())return;
    const payload={...draft,id:'shared-'+crypto.randomUUID(),name:draft.name.trim(),location:draft.location.trim(),summary:draft.summary.trim()};
    completionFocus=Boolean(document.activeElement?.closest('#shared-form'));
    pending={id:payload.id,payload};persist();busy=true;error='';onChange();
    try{const result=await api('/api/resources',payload);if(result.resource?.id!==payload.id)throw Error('invalid_resource_receipt');saved();}
    catch(e){if(e.status>=400&&e.status<500&&!e.uncertain){pending=null;persist();error=L('未保存：','Not saved: ')+text(e.message);}else error=L('结果待确认，核对原引用','Outcome unknown; check the original reference');}
    finally{busy=false;onChange();}
  }
  function render(){
    const snapshot=getSnapshot(),resources=list(snapshot.resources).filter(r=>matches(r,query)&&(category==='all'||category==='files'&&['document','directory'].includes(r.kind)||category==='resources'&&!['document','directory'].includes(r.kind)));
    const notes=list(snapshot.messages).filter(m=>['handoff','decision','reference','knowledge'].includes(m.kind)&&matches(m,query)).sort((a,b)=>(timestamp(b.created)||0)-(timestamp(a.created)||0));
    return `<section class="shared-space"><div class="shared-toolbar">${snapshot.capabilities?.project_memory?`<button class="button subtle" data-action="project-memory-open">${esc(L('项目记忆','Project memory'))}</button>`:''}<input id="shared-search" type="search" value="${esc(query)}" placeholder="${esc(L('搜索共享内容','Search shared items'))}" aria-label="${esc(L('搜索共享内容','Search shared items'))}"><button class="button subtle" data-shared="add" ${!writeReady()||snapshot.capabilities?.resource_register!==true?'disabled':''}>＋ ${esc(L('共享引用','Share reference'))}</button></div><div class="shared-kinds">${[['all',L('全部','All')],['files',L('文件','Files')],['resources',L('资源','Resources')],['notes',L('信息','Information')]].map(([id,label])=>`<button data-shared-filter="${id}" aria-pressed="${category===id}">${esc(label)}</button>`).join('')}</div>
    ${notice?`<p class="shared-confirmation" role="status">${esc(notice)}</p>`:''}${formOpen?`<form id="shared-form" class="shared-form"><label>${esc(L('名称','Name'))}<input name="name" data-shared-field maxlength="120" value="${esc(draft.name)}" required ${pending?'readonly':''}></label><label>${esc(L('文件路径或 HTTPS 链接','File path or HTTPS link'))}<input name="location" data-shared-field maxlength="2048" value="${esc(draft.location)}" required ${pending?'readonly':''}></label><div class="shared-form-row"><label>${esc(L('类型','Type'))}<select name="kind" data-shared-field ${pending?'disabled':''}>${['document','directory','repository','github','server'].map(k=>`<option value="${k}" ${draft.kind===k?'selected':''}>${kindLabel(k)}</option>`).join('')}</select></label><label>${esc(L('项目','Project'))}<select name="project" data-shared-field ${pending?'disabled':''}><option value="">${esc(L('公共','General'))}</option>${list(snapshot.projects).map(p=>`<option value="${esc(p.id)}" ${draft.project===p.id?'selected':''}>${esc(p.name||p.id)}</option>`).join('')}</select></label></div><label>${esc(L('简短说明','Short note'))}<textarea name="summary" data-shared-field maxlength="1000" rows="2" ${pending?'readonly':''}>${esc(draft.summary)}</textarea></label><small>${esc(L('登记引用，不上传文件；本地路径需要访问权限。','Reference only; files stay at their source and require access.'))}</small>${error?`<p role="status" class="cc-error">${esc(error)}</p>`:''}<div class="shared-form-actions">${pending?`<button type="button" data-shared="lookup" class="button subtle" ${busy?'disabled':''}>${esc(L('核对原引用','Check reference'))}</button>`:`<button type="button" data-shared="close" class="button subtle">${esc(L('取消','Cancel'))}</button><button type="submit" class="button primary" ${busy?'disabled':''}>${esc(L('保存','Save'))}</button>`}</div></form>`:''}
    <div class="shared-list">${category!=='notes'?resources.map(r=>`<button class="shared-row" data-key="shared:${esc(r.id)}" data-detail="resource" data-id="${esc(r.id)}"><span class="shared-type">${esc(kindLabel(r.kind))}</span><span><strong>${esc(r.name||r.id)}</strong><small>${esc(excerpt(r.summary||r.location,85))}</small></span><span class="shared-state ${esc(r.status)}">${esc(({available:L('可用','Available'),registered:L('已登记','Registered'),missing:L('缺失','Missing'),unreachable:L('不可达','Unreachable')})[r.status]||L('未知','Unknown'))}</span></button>`).join(''):''}${['all','notes'].includes(category)?notes.slice(0,30).map(m=>`<button class="shared-row shared-note" data-key="shared-note:${esc(m.id)}" data-detail="message" data-id="${esc(m.id)}"><span class="shared-type">${esc(L('信息','Note'))}</span><span><strong>${esc(messageExcerpt(m.body,72))}</strong><small>${esc(m.sender_name||m.sender)}</small></span><span>↗</span></button>`).join(''):''}</div>${!(category==='notes'?notes.length:resources.length+(category==='all'?notes.length:0))?`<p class="minimal-empty">${esc(L('暂无匹配的共享内容','No matching shared items'))}</p>`:''}</section>`;
  }
  document.addEventListener('input',e=>{if(e.target.id==='shared-search'){query=e.target.value;onChange();}if(e.target.hasAttribute?.('data-shared-field')&&!pending)draft[e.target.name]=e.target.value;});
  document.addEventListener('change',e=>{if(e.target.hasAttribute?.('data-shared-field')&&!pending)draft[e.target.name]=e.target.value;});
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.sharedFilter){category=b.dataset.sharedFilter;onChange();}if(b.dataset.shared==='add'){formOpen=!formOpen;notice='';onChange();if(formOpen)focusVisible('#shared-form [name="name"]');}if(b.dataset.shared==='close'&&!busy){formOpen=false;onChange();focusVisible('[data-shared="add"]');}if(b.dataset.shared==='lookup')void lookup();});
  document.addEventListener('submit',e=>{if(e.target.id==='shared-form'){e.preventDefault();void submit();}});
  return {render};
}
