import {esc,list,text,timestamp,normalize,taskRecordLabel} from './model.js';
import {updateHTML} from './dom.js';
import {messageExcerpt,channelTimeline} from './scene-signals.js';
import {stations,statusLabel,orderedTasks,zoomAt,validCamera,readPage} from './observer-model.js';
import {stationColor} from './command-scene.js';

const $=s=>document.querySelector(s),KEY='control-spatial-r30';
let camera=null,rows=[],detail=null,returnCamera=null,hoverId='',suppressed='',pages={},polling=false,disposed=false,saveTimer,gesture=null,dragged=false,space=false;
const sources={snapshot:{value:null},registry:{value:null}},pointers=new Map(),controllers=new Set();
const colors=new Map(),palette=['#b5c788','#91bed6','#d4a28d','#b6a3d5','#81c6b3','#d1bd7f','#d698b4','#92b29d','#93a6d8','#c2af98','#a8ccbb','#b4c5d0'];
function color(id){return colors.get(id)||stationColor('registry:'+id);}
try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(validCamera(v))camera=v;}catch{}
let language='zh';try{if(localStorage.getItem('control-language')==='en')language='en';}catch{}
const L=(zh,en)=>language==='en'?en:zh;
const clock=(at,full=false)=>{const n=timestamp(at);return Number.isFinite(n)?new Intl.DateTimeFormat(language==='en'?'en-GB':'zh-CN',full?{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}:{hour:'2-digit',minute:'2-digit',hour12:false}).format(n):L('尚无记录','No record');};
const reachable=()=>!!sources.snapshot.value&&!sources.snapshot.error&&Date.now()-sources.snapshot.at<180000&&sources.snapshot.value.connection?.state==='online';
const actor=id=>list(sources.snapshot.value?.agents).find(a=>a.id===id)?.name||id||L('未分配','Unassigned');
const body=value=>`<p>${esc(text(value)||L('暂无记录','No record'))}</p>`;
const measure=document.createElement('canvas').getContext('2d');
function nameLines(name,width){measure.font='500 12px Inter,"Segoe UI","Microsoft YaHei",sans-serif';const lines=[];let line='';for(const c of name){if(line&&measure.measureText(line+c).width>width){lines.push(line);line='';}line+=c;}lines.push(line);return lines;}
function geometry(){const mobile=innerWidth<700,w=mobile?Math.max(288,innerWidth-32):950,cols=mobile?(w>=340?2:1):Math.min(3,Math.max(rows.length,1)),scale=mobile?1:1.25;
 const extra=Math.max(0,...rows.map(s=>nameLines(s.name||s.id,mobile?137:174).length-1))*16*scale;
 const step=(mobile?177:205)+extra,h=Math.max(mobile?330:680,120+Math.ceil(rows.length/cols)*step);
 return {mobile,w,h,cols,scale,step,full:mobile?w:1390};}
function desk(s,i,g){const lines=nameLines(s.name||s.id,g.mobile?137:174),row=Math.floor(i/g.cols),n=Math.min(g.cols,rows.length-row*g.cols),x=g.w/2+(i%g.cols-(n-1)/2)*(g.mobile?g.w/2:275),y=128+row*g.step,half=g.mobile?75:95,extra=(lines.length-1)*16,state=s.status.state,label=statusLabel(state,language);
 return `<g class="floor-seat seat-${esc(state)}${detail?.type==='station'&&detail.id===s.id?' selected':''}" data-key="seat-${esc(s.id)}" data-seat="${esc(s.id)}" data-open="station" data-id="${esc(s.id)}" style="--station-accent:${color(s.id)}" transform="translate(${x} ${y}) scale(${g.scale})" role="button" tabindex="0" aria-label="${esc((s.name||s.id)+' · '+label)}" aria-pressed="${detail?.type==='station'&&detail.id===s.id}"><ellipse class="work-orbit" cx="0" cy="23" rx="69" ry="34"/><ellipse class="seat-shadow" cx="0" cy="29" rx="60" ry="19"/><path class="seat-plinth" d="M-62 8 0-24 64 8 1 43Z"/><path class="desk-side" d="M-49-1 0 23 49-1V8L0 33-49 8Z"/><path class="desk-top" d="M-49-1 0-26 49-1 0 23Z"/><path class="desk-leg" d="M-41 11v21m82-21v21"/><path class="monitor-back" d="M-25-43 13-25 13 4-25-14Z"/><path class="monitor-screen" d="M-20-35 8-21 8-4-20-18Z"/><path class="monitor-lines" d="M-16-29 4-19 M-16-24-2-17 M-16-19-5-13"/><path class="keyboard" d="M-2 5 12-2 26 5 12 12Z"/><path class="seat-chair" d="M-11 27 2 20 18 28 5 35Z M-11 27v12l16 8 13-8V28"/><circle class="seat-signal" cx="42" cy="-3" r="3"/><g class="seat-caption" transform="translate(0 65)"><rect x="${-half}" y="-14" width="${half*2}" height="${43+extra}" rx="7"/><text text-anchor="middle" class="seat-name">${lines.map((line,j)=>`<tspan x="0" y="${j*16}">${esc(line)}</tspan>`).join('')}</text><text text-anchor="middle" y="${19+extra}" class="seat-state">${esc(label)}</text></g></g>`;}
function floor(g){const grid=Array.from({length:Math.ceil(g.w/80)},(_,i)=>`<path d="M${20+i*80} 56V${g.h-18}"/>`).join('')+Array.from({length:Math.ceil(g.h/80)},(_,i)=>`<path d="M12 ${60+i*80}H${g.w-12}"/>`).join('');return `<section id="space-stations" class="office-floor" data-domain="stations" style="width:${g.w}px;height:${g.h}px" aria-labelledby="stations-title"><div class="office-heading"><h1 id="stations-title" tabindex="0">${L('工位','Workstations')}</h1><output>${rows.length}</output><span id="sync-note" role="status">${sources.snapshot.error||sources.registry.error?L('更新待恢复 · 保留记录','Updates paused · records retained'):''}</span></div><span class="office-hint">${L('拖动空白处 · 滚轮缩放 · 双击归位','Drag to pan · Scroll to zoom · Double-click to reset')}</span><svg viewBox="0 0 ${g.w} ${g.h}" aria-label="${L('工位空间','Office space')}"><defs><linearGradient id="floor-fill" x2="0" y2="1"><stop stop-color="#222932"/><stop offset="1" stop-color="#141a22"/></linearGradient></defs><g class="room-scenery"><rect class="room-base" x="0" y="57" width="${g.w}" height="${g.h-58}" rx="24"/><rect class="room-floor" x="0" y="47" width="${g.w}" height="${g.h-58}" rx="24"/><g class="floor-grid">${grid}</g><path class="wall-edge" d="M24 48H${g.w-24}"/></g>${rows.map((s,i)=>desk(s,i,g)).join('')}</svg>${!rows.length?`<p class="space-empty-floor">${L(sources.registry.error?'工位资料暂时无法读取，恢复后自动更新。':'等待工位接入','Waiting for workstations')}</p>`:''}</section>`;}
const pageSources=new Map();
function panel(id,title,items,size,renderItem,empty){pageSources.set(id,items);const p=readPage(items,pages[id],size);return `<section id="space-${id}" data-domain="${id}" class="space-panel" aria-labelledby="${id}-title"><header><h2 id="${id}-title" tabindex="0">${title}</h2>${p.total>size?`<div class="panel-pages"><button data-page="${id}" data-start="${p.previous}" ${p.start===0?'disabled':''} aria-label="${L('较新记录','Newer records')}">‹</button><span>${p.start+1}–${p.start+p.items.length} / ${p.total}</span><button data-page="${id}" data-start="${p.next}" ${!p.hasNext?'disabled':''} aria-label="${L('较早记录','Older records')}">›</button></div>`:`<span>${p.total}</span>`}</header><div class="panel-body">${p.items.map(renderItem).join('')||`<p class="space-empty">${empty}</p>`}</div></section>`;}
function message(m){const r=m.message||m.delivery||m,type=m.message||m.sender?'message':'delivery';return `<article class="cc-chat-message" data-key="${esc(m.id)}"><header><strong>${esc(r.sender_name||actor(r.sender||r.target))}</strong><time>${esc(clock(m.at||r.created))}</time></header><p>${esc(messageExcerpt(r.body,80))}</p><button class="chat-expand" data-open="${type}" data-id="${esc(r.id)}">${L('全文','Read more')}</button></article>`;}
function task(t){return `<button class="space-task" data-key="task-${esc(t.id)}" data-open="task" data-id="${esc(t.id)}"><span class="task-status">${esc(taskRecordLabel(t,language,reachable()))}</span><strong>${esc(t.title||t.id)}</strong><small>${esc(actor(t.owner))}</small></button>`;}
function detailMarkup(){if(!detail)return '';const snap=sources.snapshot.value||{};let title='',content='';
 if(detail.type==='station'){const s=rows.find(s=>s.id===detail.id)||detail.record,current=rows.find(s=>s.id===detail.id);title=L('工位','Workstation');content=`<h3>${esc(s.name||s.id)}</h3><p class="detail-meta">${esc(statusLabel(current?.status.state||'sync',language))} · ${esc(s.project||'')}</p><h4>${L('最近动态','Recent activity')}</h4>`+(s.messages?.slice(0,6).map(m=>`<article><time>${esc(clock(m.created,true))}</time>${body(m.body)}</article>`).join('')||body(L('暂无已记录动态。等待下一次状态同步。','Awaiting a recorded update.')))+`<h4>${L('任务','Tasks')}</h4>`+(s.tasks?.map(task).join('')||body(L('暂无登记任务','No registered tasks')));}
 else if(detail.type==='task'){const t=list(snap.tasks).find(t=>t.id===detail.id)||detail.record;title=L('任务','Task');content=`<h3>${esc(t.title||t.id)}</h3><p class="detail-meta">${esc(taskRecordLabel(t,language,reachable()))} · ${esc(actor(t.owner))}</p>${body(t.description||t.summary||t.body||t.title)}${t.evidence?`<h4>${L('交付记录','Delivery record')}</h4>${body(t.evidence)}`:''}`;}
 else{const r=list(snap[detail.type==='message'?'messages':'deliveries']).find(m=>m.id===detail.id)||detail.record;title=L('群聊','Conversation');content=`<h3>${esc(r.sender_name||actor(r.sender||r.target))}</h3><p class="detail-meta">${esc(clock(r.created||r.created_at,true))}</p>${body(r.body)}${r.reply?body(r.reply):''}`;}
 return `<section id="space-detail" class="space-panel space-detail" aria-labelledby="detail-title"><header><h2 id="detail-title" tabindex="-1">${title}</h2><button class="space-close" data-close aria-label="${L('收起详情','Close detail')}">×</button></header><div class="panel-body">${content}</div></section>`;}
function render(){const oldHover=hoverId;rows=stations(sources.registry.value,sources.snapshot.value,reachable()&&!sources.registry.error);const used=new Set(colors.values());for(const s of [...rows].sort((a,b)=>a.id.localeCompare(b.id))){if(colors.has(s.id))continue;let c=stationColor('registry:'+s.id);if(used.has(c))c=palette.find(p=>!used.has(p))||c;colors.set(s.id,c);used.add(c);}const g=geometry(),snap=sources.snapshot.value||{};updateHTML($('#office-world'),floor(g)+panel('chat',L('群聊','Conversation'),channelTimeline(snap).reverse(),3,message,L('等待工位的新消息','Waiting for messages'))+panel('tasks',L('任务','Tasks'),orderedTasks(snap.tasks,reachable()),3,task,L('暂无登记任务','No registered tasks'))+detailMarkup());layout(g);if(!camera)home();else applyCamera(false);if(oldHover)showHover(oldHover);$('#main').dataset.ready='true';}
function layout(g=geometry()){const chat=$('#space-chat'),tasks=$('#space-tasks'),width=g.mobile?g.w:400;chat.style.width=tasks.style.width=width+'px';chat.style.left=tasks.style.left=(g.mobile?0:990)+'px';chat.style.top=(g.mobile?g.h+38:47)+'px';tasks.style.top=(chat.offsetTop+chat.offsetHeight+30)+'px';const d=$('#space-detail');if(d){d.style.width=(g.mobile?g.w:480)+'px';d.style.left=(g.mobile?g.w+40:1430)+'px';d.style.top='47px';}}
function applyCamera(save=true){$('#office-world').style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.z})`;$('#main').style.backgroundPosition=`${camera.x}px ${camera.y}px`;hideHover();if(save){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify(camera));}catch{}},180);}}
function home(){const g=geometry(),z=g.mobile?1:Math.min(1,Math.max(.55,(innerWidth-48)/g.full));camera={x:g.mobile?16:(innerWidth-g.full*z)/2,y:22,z};applyCamera();}
function focusElement(el){const r=el.getBoundingClientRect();if(r.left>=12&&r.right<=innerWidth-12&&r.top>=12&&r.bottom<=innerHeight-12)return;const g=geometry(),b=el.closest('.space-panel,.office-floor'),w=b.offsetWidth,z=Math.min(1.1,(innerWidth-32)/w);camera={z,x:16-b.offsetLeft*z,y:22-b.offsetTop*z};applyCamera();const rr=el.getBoundingClientRect();if(rr.bottom>innerHeight-20||rr.top<20){camera.y+=Math.max(24,(innerHeight-rr.height)/2)-rr.top;applyCamera();}}
function open(type,id){const snap=sources.snapshot.value||{},record=type==='station'?rows.find(s=>s.id===id):list(snap[type==='task'?'tasks':type==='message'?'messages':'deliveries']).find(r=>r.id===id);if(!record)return;if(!detail)returnCamera={...camera};detail={type,id,record};hideHover();render();const el=$('#space-detail'),z=Math.min(1,(innerWidth-32)/el.offsetWidth);camera={x:(innerWidth-el.offsetWidth*z)/2-el.offsetLeft*z,y:22-el.offsetTop*z,z};applyCamera();$('#detail-title').focus({preventScroll:true});}
function close(){if(!detail)return;const old=detail;detail=null;render();if(returnCamera){camera=returnCamera;returnCamera=null;applyCamera();}const el=[...document.querySelectorAll('[data-open]')].find(e=>e.dataset.open===old.type&&e.dataset.id===old.id);el?.focus({preventScroll:true});hideHover();suppressed=old.id;}
function hideHover(){hoverId='';$('#space-hover').hidden=true;document.querySelectorAll('[aria-describedby="space-hover"]').forEach(e=>e.removeAttribute('aria-describedby'));}
function showHover(id){if(suppressed===id||gesture)return;const s=rows.find(s=>s.id===id),el=[...document.querySelectorAll('[data-seat]')].find(e=>e.dataset.seat===id);if(!s||!el)return;hoverId=id;const tip=$('#space-hover');tip.innerHTML=`<strong>${esc(s.name||s.id)}</strong><small>${esc(statusLabel(s.status.state,language))}</small><p>${esc(messageExcerpt(s.messages[0]?.body||L('暂无新动态，等待工位同步。','Awaiting a workstation update.'),90))}</p>`;tip.hidden=false;el.setAttribute('aria-describedby','space-hover');const r=el.getBoundingClientRect(),w=tip.offsetWidth,h=tip.offsetHeight;tip.style.left=Math.max(12,Math.min(innerWidth-w-12,r.right+12))+'px';tip.style.top=Math.max(12,Math.min(innerHeight-h-12,r.top))+'px';}
async function refresh(){if(polling||disposed)return;polling=true;$('#main').dataset.refreshing='true';await Promise.all(Object.keys(sources).map(async key=>{const controller=new AbortController();controllers.add(controller);const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch('/api/'+key,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('read');const v=await r.json();if(key==='snapshot'?!['agents','messages','tasks','resources','projects'].every(k=>Array.isArray(v?.[k])):!Array.isArray(v?.seats)||!Array.isArray(v?.governance))throw Error('shape');sources[key]={value:key==='snapshot'?normalize(v):v,at:Date.now(),error:false};}catch{sources[key].error=true;}finally{clearTimeout(timer);controllers.delete(controller);}}));polling=false;if(disposed)return;render();$('#main').dataset.refreshing='false';}

document.documentElement.lang=language==='en'?'en':'zh-CN';
$('#app').innerHTML=`<main id="main" class="office-space" tabindex="0" aria-label="${L('工位、群聊与任务。拖动平移，滚轮缩放，Home归位。数字1、2、3定位三个区域。','Workstations, conversation and tasks. Drag to pan, scroll to zoom, Home to reset. Keys 1, 2, 3 focus each area.')}"><div id="office-world"></div></main><aside id="space-hover" class="space-hover" role="tooltip" hidden></aside>`;
const main=$('#main');
main.addEventListener('click',e=>{if(dragged)return;if(e.target.closest('[data-close]'))return close();const p=e.target.closest('[data-page]');if(p){const items=pageSources.get(p.dataset.page)||[],start=Number(p.dataset.start);pages[p.dataset.page]={start,anchor:start?items[start]?.id:null};render();return;}const b=e.target.closest('[data-open]');if(b)open(b.dataset.open,b.dataset.id);});
main.addEventListener('dblclick',e=>{if(!e.target.closest('.space-panel,[data-seat]'))home();});
main.addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const s=e.target.closest('[data-seat]');if(s)showHover(s.dataset.seat);});
main.addEventListener('pointerout',e=>{const s=e.target.closest('[data-seat]');if(s&&!s.contains(e.relatedTarget)){suppressed='';hideHover();}});
main.addEventListener('focusin',e=>{if(e.target===main||e.target.id==='detail-title')return;focusElement(e.target);const s=e.target.closest('[data-seat]');if(s)showHover(s.dataset.seat);});
main.addEventListener('wheel',e=>{e.preventDefault();if(e.shiftKey){camera.x-=e.deltaY;camera.y-=e.deltaX;}else camera=zoomAt(camera,Math.exp(-e.deltaY*.0012),{x:e.clientX,y:e.clientY});applyCamera();},{passive:false});
main.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});dragged=false;if(pointers.size===2){const [a,b]=[...pointers.values()];gesture={type:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},camera:{...camera}};hideHover();main.setPointerCapture(e.pointerId);return;}const interactive=e.target.closest('button,[data-seat],h1,h2');if(interactive&&e.pointerType!=='touch'&&!space)return;gesture={type:'pan',id:e.pointerId,x:e.clientX,y:e.clientY,camera:{...camera},pending:!!interactive};if(!interactive)main.setPointerCapture(e.pointerId);});
main.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!gesture)return;if(gesture.type==='pinch'&&pointers.size===2){const [a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};camera=zoomAt(gesture.camera,Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,gesture.distance),gesture.center);camera.x+=center.x-gesture.center.x;camera.y+=center.y-gesture.center.y;dragged=true;applyCamera();return;}if(gesture.type==='pan'&&e.pointerId===gesture.id){const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)<5)return;dragged=true;main.setPointerCapture(e.pointerId);camera={...gesture.camera,x:gesture.camera.x+dx,y:gesture.camera.y+dy};applyCamera();}});
function endPointer(e){pointers.delete(e.pointerId);gesture=null;if(main.hasPointerCapture(e.pointerId))main.releasePointerCapture(e.pointerId);setTimeout(()=>{if(!pointers.size)dragged=false;},0);}
main.addEventListener('pointerup',endPointer);main.addEventListener('pointercancel',endPointer);main.addEventListener('lostpointercapture',()=>{if(!pointers.size)gesture=null;});
document.addEventListener('keydown',e=>{if(e.isComposing)return;if(e.key==='Escape'){e.preventDefault();if(hoverId){suppressed=hoverId;hideHover();}else close();return;}if(e.key===' '){const b=e.target.closest('[data-seat]');if(b){e.preventDefault();open('station',b.dataset.seat);return;}space=true;}const seat=e.target.closest('[data-seat]');if(seat&&e.key==='Enter'){e.preventDefault();open('station',seat.dataset.seat);return;}if(['Home','+','=','-','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','1','2','3'].includes(e.key)){e.preventDefault();if(e.key==='Home')home();else if(['1','2','3'].includes(e.key)){const el=$('#'+['stations-title','chat-title','tasks-title'][Number(e.key)-1]);focusElement(el);el.focus({preventScroll:true});}else if(['+','=','-'].includes(e.key)){camera=zoomAt(camera,e.key==='-'?.85:1.18,{x:innerWidth/2,y:innerHeight/2});applyCamera();}else{camera.x+=({ArrowLeft:70,ArrowRight:-70})[e.key]||0;camera.y+=({ArrowUp:70,ArrowDown:-70})[e.key]||0;applyCamera();}}});
document.addEventListener('keyup',e=>{if(e.key===' ')space=false;});
window.addEventListener('blur',()=>{pointers.clear();gesture=null;space=false;hideHover();});
window.addEventListener('resize',()=>{render();home();});
window.addEventListener('pagehide',()=>{disposed=true;clearInterval(timer);controllers.forEach(c=>c.abort());});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
render();refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},8000);
